// Field Notes of Wonder: restrained interaction keeps attention on real photographs, human stories, and accessible bilingual reading.
const copy = {
  vi: { navJourney:'Hành trình', navAi:'AI & con người', navGallery:'Khoảnh khắc', navFilm:'Video', eyebrow:'TRẠI HÈ NGÔN NGỮ & NGHỆ THUẬT · 2026', heroTitle:'Một mùa hè, nhiều tiếng nói tự tin hơn.', heroLede:'Một tuần học tập, trải nghiệm và sẻ chia khép lại — nhưng tiếng cười, tiếng hát và niềm tin “Mình có thể” vẫn còn ở lại.', heroCta:'Xem hành trình <span>↘</span>', location:'Trường TH & THCS Hưng Đạo · Tháng 8 năm 2026', factOne:'bạn nhỏ cùng tạo nên mùa hè này', factTwo:'buổi sáng học, thực hành và kết nối', factThree:'ngày hội khép lại bằng những tiết mục rạng rỡ', chapterOne:'CHƯƠNG 01 · HỌC, LẮNG NGHE, THỬ SỨC', journeyTitle:'Từ một âm tiết đến một bước tiến dũng cảm.', journeyBody:'Những giờ học không chỉ xoay quanh việc phát âm đúng. Mỗi lần giơ tay, mỗi bài tập được hoàn thành và mỗi cuộc trò chuyện đều là một cơ hội để học sinh khám phá tiếng nói của chính mình.', tagOne:'Lắng nghe chủ động', tagTwo:'Kỹ năng số', tagThree:'Cộng tác cùng nhau', captionTeach:'Một lớp học mở ra cho sự tham gia.', captionCreate:'Ý tưởng lớn lên từ một trang giấy nhỏ.', quote:'“Điều đẹp nhất không phải là các em phát âm được bao nhiêu từ. Đó là khoảnh khắc các em dám nói.”', chapterTwo:'CHƯƠNG 02 · AI VÀ SỰ DẪN DẮT CỦA CON NGƯỜI', aiTitle:'AI có thể mở rộng lớp học. Người thầy mới tạo nên hành trình.', aiBody:'AI đang thay đổi cách chúng ta học: gợi ý bài luyện tập phù hợp hơn, phản hồi nhanh hơn và mở ra nhiều cách để khám phá. Nhưng AI không thay thế được ánh mắt động viên, sự kiên nhẫn hay khả năng nhìn thấy tiềm năng riêng của mỗi đứa trẻ.', aiPointOne:'AI giúp việc thực hành trở nên linh hoạt và cá nhân hóa hơn.', aiPointTwo:'Người dạy vẫn là người đặt câu hỏi, tạo an toàn và nuôi dưỡng niềm tin.', aiPointThree:'Khi công nghệ và sự quan tâm gặp nhau, nhiều điều tốt hơn có thể diễn ra.', galleryEyebrow:'NHẬT KÝ HÌNH ẢNH', galleryTitle:'42 khoảnh khắc. Một ký ức chung.', galleryText:'Tất cả hình ảnh dưới đây là tư liệu gốc do chương trình cung cấp, được sắp xếp lại để kể trọn hành trình từ lớp học đến những nụ cười cuối ngày.', filmEyebrow:'THƯỚC PHIM HÀNH TRÌNH', filmTitle:'Những điều không nằm yên trong một bức ảnh.', filmText:'Một thước phim ghi lại những giờ học, những cánh tay giơ lên, những bài tập được hoàn thành và sự kết nối làm nên một mùa hè đáng nhớ.', thanksEyebrow:'CHƯƠNG CUỐI · CẢM ƠN', thanksTitle:'Đằng sau mỗi nụ cười là một vòng tay đồng hành.', thanksBody:'Trường TH & THCS Hưng Đạo trân trọng cảm ơn VinUniversity, nhóm nghiên cứu, các giảng viên, nghiên cứu sinh, sinh viên, đội ngũ tình nguyện viên và phụ huynh. Cảm ơn 50 bạn nhỏ — những nhân vật chính của hành trình này.', footerQuote:'Giáo dục không chỉ là truyền đạt kiến thức. Giáo dục còn là giúp mỗi đứa trẻ tin rằng: “Mình có thể.”', photoLabel:'Khoảnh khắc trại hè' },
  en: { navJourney:'The journey', navAi:'AI & people', navGallery:'Moments', navFilm:'Film', eyebrow:'LANGUAGE & ARTS SUMMER CAMP · 2026', heroTitle:'One summer. Many more confident voices.', heroLede:'A week of learning, discovery and shared care has come to a close — but the laughter, songs and belief that “I can” remain.', heroCta:'Follow the journey <span>↘</span>', location:'Hung Dao Primary & Secondary School · August 2026', factOne:'young learners shaped this summer together', factTwo:'mornings of learning, practice and connection', factThree:'closing celebration filled with bright performances', chapterOne:'CHAPTER 01 · LEARN, LISTEN, TRY', journeyTitle:'From one syllable to one brave step forward.', journeyBody:'The sessions were about more than pronunciation. Every raised hand, completed activity and conversation gave learners another chance to discover their own voice.', tagOne:'Active listening', tagTwo:'Digital literacy', tagThree:'Learning together', captionTeach:'A classroom open to participation.', captionCreate:'Big ideas begin on a small sheet of paper.', quote:'“The best part is not how many words children pronounce. It is the moment they dare to speak.”', chapterTwo:'CHAPTER 02 · AI AND HUMAN GUIDANCE', aiTitle:'AI can expand the classroom. Teachers make the journey meaningful.', aiBody:'AI is changing how we learn: it can suggest more suitable practice, offer faster feedback and open new paths to discovery. Yet it cannot replace an encouraging look, patient guidance or the ability to see the unique potential in every child.', aiPointOne:'AI can make practice more flexible and personal.', aiPointTwo:'Teachers still ask the questions, create safety and nurture belief.', aiPointThree:'When technology meets care, more good things become possible.', galleryEyebrow:'PHOTO JOURNAL', galleryTitle:'42 moments. One shared memory.', galleryText:'Every image below is original programme material, thoughtfully arranged to tell the journey from the classroom to the final smiles of the day.', filmEyebrow:'THE JOURNEY ON FILM', filmTitle:'The things a single photograph cannot hold.', filmText:'A short film of lessons, raised hands, finished activities and the connections that made this summer memorable.', thanksEyebrow:'FINAL CHAPTER · THANK YOU', thanksTitle:'Behind every smile is a circle of care.', thanksBody:'Hung Dao Primary & Secondary School warmly thanks VinUniversity, the research group, lecturers, graduate researchers, students, volunteers and families. And thank you to the 50 young learners — the main characters of this journey.', footerQuote:'Education is not only about passing on knowledge. It is also about helping every child believe: “I can.”', photoLabel:'Summer camp moment' }
};

Object.assign(copy.vi, { filmEyebrow: 'MONTAGE ẢNH', filmTitle: 'Ảnh kể lại một mùa hè.' });
Object.assign(copy.en, { filmEyebrow: 'PHOTO MONTAGE', filmTitle: 'A summer, in still frames.' });

const grid = document.querySelector('#photo-grid');
const dialog = document.querySelector('#lightbox');
const dialogImage = document.querySelector('#lightbox-image');
const dialogCaption = document.querySelector('#lightbox-caption');
let language = 'en';

function photoLabel(number) { return `${copy[language].photoLabel} ${String(number).padStart(2, '0')}`; }
function renderGallery() {
  grid.innerHTML = Array.from({ length: 42 }, (_, index) => {
    const number = index + 1;
    const padded = String(number).padStart(2, '0');
    return `<button class="photo-card" type="button" data-photo="${padded}" aria-label="${photoLabel(number)}"><img src="media/${padded}.webp" alt="${photoLabel(number)}" loading="lazy" /><span>${padded} / 42</span></button>`;
  }).join('');
}
function applyLanguage(nextLanguage) {
  language = nextLanguage;
  document.documentElement.lang = language;
  document.querySelectorAll('[data-i18n]').forEach((node) => { node.innerHTML = copy[language][node.dataset.i18n]; });
  document.querySelectorAll('.lang-btn').forEach((button) => { const selected = button.dataset.lang === language; button.classList.toggle('active', selected); button.setAttribute('aria-pressed', String(selected)); });
  renderGallery();
}
document.querySelectorAll('.lang-btn').forEach((button) => button.addEventListener('click', () => applyLanguage(button.dataset.lang)));
grid.addEventListener('click', (event) => { const card = event.target.closest('.photo-card'); if (!card) return; const number = Number(card.dataset.photo); dialogImage.src = `media/${card.dataset.photo}.webp`; dialogImage.alt = photoLabel(number); dialogCaption.textContent = photoLabel(number); dialog.showModal(); });
document.querySelector('#close-lightbox').addEventListener('click', () => dialog.close());
dialog.addEventListener('click', (event) => { if (event.target === dialog) dialog.close(); });
applyLanguage(language);
